- name: Configure FreeIPA
  hosts: all
  become: true
  vars:
    ipa_server: "ipa.otus.lan"
    domain: "otus.lan"
    realm: "OTUS.LAN"
    admin_account: "admin"
    admin_password: "Qazwsx123"
    netbios: "OTUS"
    user_account: "Otus"
    user_password: "Otus2025"
    user_first: "Otus"
    user_last: "Test"
    user_shell: "/bin/bash"
    pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCiOH1KarUNP+hC6erbK7LlkFwaB4Qb8zkdEjC5SSPLS5rFqRq9BlW79HViCQQRmYtgkCc3m2oQuVegwzlYsKVJmICVEeNr/sUYa22317ZOljKJCXwT8mj7PoW+Fg8v94W5gjSqWLZXAZ9v7F/1wJZUYhvLaNca2H97gWoVAh7e3RDDUR8rLQsMYLIwcJDWfC2sHOVKUw//gF7/jrvHDqbWCcKk9jA7HpM4Vn3UcKYRIzuI209pMoy1jrLdzBHse6b1gJmJfmt0YrbohBk+4w9wUs4d7qRRESNxkix1DjYLrqpsssLiae2cH4IWIP6NktwKDcNARt1lZnWv2/9ECIf1Ah8gMNsmgyQPrxIg7AvKkKceNCiLj+1RdLeSYzPe9kzYKJFYKf6Pa82qgE6Uc7WDb17r0nNyj4g/wZ3s8N/b7iIswfV7Q0JoiZI+LsDqJdvxkE5/WhwMnc6Ij85q0JxIlDDEgCobxHWbueVTogyARsQl5KpgdvNDK8BDoCuhDs= root@ipa.otus.lan"

- name: Configure FreeIPA Server
  hosts: ipa
  become: yes
  roles:
    - freeipa-server

- name: Configure IPA Clients
  hosts: clients
  become: yes
  roles:
    - freeipa-client